"use client";

import React from "react";
import {
  Page,
  Text,
  View,
  Document,
  StyleSheet,
  PDFDownloadLink,
} from "@react-pdf/renderer";

// ========================
// 📄 STYLES
// ========================
const styles = StyleSheet.create({
  page: {
    backgroundColor: "#f9fafb",
    padding: 24,
    fontFamily: "Helvetica",
    fontSize: 12,
    lineHeight: 1.5,
  },
  header: {
    fontSize: 18,
    color: "#1e3a8a",
    marginBottom: 8,
    fontWeight: "bold",
  },
  subHeader: {
    fontSize: 12,
    color: "#4b5563",
    marginBottom: 20,
  },
  section: {
    marginBottom: 20,
    paddingBottom: 10,
    borderBottom: "1px solid #d1d5db",
  },
  label: {
    fontSize: 14,
    color: "#2563eb",
    marginBottom: 6,
    fontWeight: "bold",
  },
  barBackground: {
    height: 6,
    backgroundColor: "#e5e7eb",
    borderRadius: 4,
    overflow: "hidden",
    marginTop: 4,
    marginBottom: 8,
  },
  barFill: {
    height: 6,
    borderRadius: 4,
  },
  footer: {
    marginTop: 24,
    fontSize: 10,
    color: "#6b7280",
    textAlign: "center",
  },
});

// ========================
// 📘 REPORT DOCUMENT
// ========================
interface ReportPDFProps {
  customer: { customer_id: string };
  summary: {
    english?: string;
    hindi?: string;
    marathi?: string;
  };
  confidence: number;
  reason: string;
}

const ReportPDF: React.FC<ReportPDFProps> = ({
  customer,
  summary,
  confidence,
  reason,
}) => {
  const barColor =
    confidence >= 80
      ? "#10B981"
      : confidence >= 60
      ? "#FACC15"
      : "#EF4444";

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <Text style={styles.header}>⚡ WattAudit++ AI Report</Text>
        <Text style={styles.subHeader}>
          Customer ID: {customer.customer_id}
        </Text>

        {/* Summary */}
        <View style={styles.section}>
          <Text style={styles.label}>🧠 Explainable AI Summary</Text>
          <Text>English: {summary.english}</Text>
          <Text>हिन्दी: {summary.hindi}</Text>
          <Text>मराठी: {summary.marathi}</Text>
        </View>

        {/* AI Insights */}
        <View style={styles.section}>
          <Text style={styles.label}>🤖 AI Explainability Insights</Text>
          <Text>
            Confidence Score: {confidence.toFixed(2)}%
          </Text>
          <View style={styles.barBackground}>
            <View
              style={{
                ...styles.barFill,
                width: `${confidence}%`,
                backgroundColor: barColor,
              }}
            />
          </View>
          <Text>Reason: {reason}</Text>
        </View>

        {/* Footer */}
        <Text style={styles.footer}>
          Generated by WattAudit++ Explainable AI |{" "}
          {new Date().toLocaleString()}
        </Text>
      </Page>
    </Document>
  );
};

// ========================
// 📥 DOWNLOAD COMPONENT
// ========================
export const ReportPDFDownload: React.FC<ReportPDFProps> = (props) => (
  <PDFDownloadLink
    document={<ReportPDF {...props} />}
    fileName={`WattAudit_Report_${props.customer.customer_id}.pdf`}
  >
    {({ loading }) => (
      <button
        className={`px-4 py-2 rounded-lg font-semibold transition ${
          loading
            ? "bg-gray-400 text-gray-200 cursor-not-allowed"
            : "bg-blue-600 text-white hover:bg-blue-700 shadow"
        }`}
      >
        {loading ? "Generating PDF..." : "⬇️ Download AI Report (PDF)"}
      </button>
    )}
  </PDFDownloadLink>
);

export default ReportPDFDownload;
